name: log-cache

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: log-cache
  version: latest
- name: bosh-dns
  version: latest

addons:
- name: bosh-dns
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns

instance_groups:
- name: log-cache
  azs:
  - z1
  - z2
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache
    release: log-cache
    consumes:
      reverse_log_proxy: {from: reverse_log_proxy, deployment: loggregator}
    properties:
      egress_port: 8080
      health_port: 6060
      logs_provider:
        tls:
          ca_cert: "((logs_provider.ca))"
          cert: "((logs_provider.certificate))"
          key: "((logs_provider.private_key))"
  - name: expvar-scraper
    release: log-cache
    properties:
      health_addr: localhost:6060/debug/vars
      datadog:
        host: ((system_domain))
        api_key: ((datadog_api_key))
      metrics:
        namespace: LogCache
        map:
          Egress: "log-cache.egress"
          Ingress: "log-cache.ingress"
          Expired: "log-cache.expired"
          CachePeriod: "log-cache.cache_period"

variables:
- name: logs_provider
  type: certificate
  options:
    ca: loggregator_ca
    common_name: log-cache
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
